### ISSUE TITLE
Glitch in animation when zooming in

### ISSUE THREAD

**Issue by ihabovich** [terrymun/Fluidbox#103] opened 2015-02-05 10:27 UTC
I just updated to last version when I found missing smoothness transition when zoom in.
I checked your demo page which got the same issue too.

Tested platforms:
Mozilla Firefox 35.0.1
Google Chrome 40.0.2214.94

**Comment by terrymun** [comment] 2015-02-05 10:29
Can you describe what does "missing smoothness" mean? I do not seem to be able to replicate your problem in Firefox, Chrome and Safari.

**Comment by ihabovich** [comment] 2015-02-05 10:53
There was a smooth animation on zooming in in earlier version. Now as you see, on image click the zoom animation is fine first time but on repeating it losses zoom animation.

![567686735ad733c64dcba25b969a9a1a](https://cloud.githubusercontent.com/assets/6496135/6058987/80de724c-ad35-11e4-8436-f6e2d90e8212.gif)

**Comment by terrymun** [comment] 2015-02-05 11:35
That is a known issue with Safari. I am unable to reproduce the bug in Chrome and Firefox. 

Closed as a duplicate of #102.

**Closed by terrymun** 2015-02-05 11:35 UTC
Labels: bug
