### ISSUE TITLE
Tut : How to make Fluidbox works with Lazysizes

### ISSUE THREAD

**Issue by l2aelba** [terrymun/Fluidbox#180] opened 2016-10-26 13:27 UTC
**I just made a tuturial + tricks here** _(Since many issues about this)_

I will show how to get it work with https://github.com/aFarkas/lazysizes

**HTML :**

```html
<a class="lazy-fluidbox" href="#"><img class="lazyload" data-src="#"></a>
```

**JS :**
```javascript
document.addEventListener('lazybeforeunveil', function(e){
	// Fluixbox
	setTimeout(function(){
		$(e.target).parent('.lazy-fluidbox').fluidbox({loader:true}); 
	},100);
});
```

**Done !**

**Any better trick, so just well come**

**Comment by terrymun** [comment] 2016-10-26 15:19
Thanks for the suggestion. It is probably useful for others who are working with Lazysizes, even though there have been no reported issues about integrating the two.

I believe it's a matter of implementation and not a bug itself, so I will be closing this.

**Closed by terrymun** 2016-10-26 15:19 UTC

**Comment by l2aelba** [comment] 2016-10-27 07:16
@terrymun Yep, just close this. Maybe I useful for someone who's searching

**Comment by olafgleba** [comment] 2020-05-24 21:47
Sadly this doesn't work when using `data-srcset` (instead of `data-src`). And i am afraid i have no solution to this so far.
