### ISSUE TITLE
Animations issues

### ISSUE THREAD

**Issue by smutnyleszek** [terrymun/Fluidbox#96] opened 2015-01-25 21:50 UTC
I started a quick project and decided to use Fluidbox for image gallery. I use Fluidbox 1.4.3 and jQuery 1.11.1. The website is http://lunabynw.com/ (https://github.com/smutnyleszek/lunabynw-com) and I have some visual issues with animations:

![fluidbox-animation-issue](https://cloud.githubusercontent.com/assets/2521888/5893432/07e1af84-a4e4-11e4-9315-12c274f64323.gif)

On latest Chrome and Safari the "loading square" is completely static and the image opening animation is not working after the first time. On latest Firefox the "loading square" works, but the opening **and** closing animation is not working at all. There is also a z-index problem with closing animation - the image being closed is behind all the previous ones.

The same opening and closing animation problems I'm experiencing on your demo page.

I'm running Fluidbox with default configuration:

```
$('a[rel="lightbox"]').fluidbox();
```

**Comment by terrymun** [comment] 2015-01-26 08:48
I have forgotten to add that the loading animations are powered by CSS3 animations, so you might want to include vendor prefixes manually in the CSS file, or use [prefixfree.js](https://github.com/LeaVerou/prefixfree/) to add appropriate vendor prefixes without any modifications to the CSS file.

I am unable to replicate your issue with the latest version of Chrome, v41. In Safari it is not working due to the requirement for the `-webkit-` prefixes for both CSS transform and animation.

Will include that missing information in the readme.

**Comment by maxee** [comment] 2015-02-23 14:09
I can reproduce this issue running Chrome 40 on Win7 64 and Chrome 40 on Android 5.0.2. The Fluidbox works correctly when one clicks on the image for the first time. Afterwards clicking on it results in the issue above.

**Comment by dergraph** [comment] 2015-03-22 14:22
yea sadly I have that problem with the opening animation too…
really bugs me, cuz its ruins the elegance of the plugin.


as far as the loader goes, I have a comment: 
it seems the loader/spinner is constantly animated. 
I would say that is not a good idea, depending on how many instances there are 
this can have a bad impact on the sites performance. 

I have noticed performance problems with animations, particularly with rotation… 

regardless of that I would say a spinner should only spin when its indicating a loading process, 
that can be done via a css rule, once loading is happening and a class is toggled. 

But personally I would wanna remove the loading spinner all together…

**Comment by terrymun** [comment] 2015-03-22 15:17
There is a yet-to-be-fixed issue with the loading, but if you toggle the `immediateOpen` option to true, that should solve the issue (as far as I know).

The loading animation is done with the CSS rule (`.fluidbox-loading`) via a pseudo-element. You can comment it out and/or override is as of when you see fit.

**Comment by dergraph** [comment] 2015-03-22 15:20
yea I already did removed it from the css.
my critique is that animation is currently spinning constantly.
so anyone whos not removing the element is having animated elements that are being calculated. (my asssumption atleast)

**Comment by terrymun** [comment] 2015-03-22 15:25
I can't seem to produce your issue of two concurrent spinning loaders. There is no constantly spinning element (unless you have an image that takes an extended amount of time to load) because the spinning animation is only enabled when the `.fluidbox-loading` class is assigned. The class is being toggled in between states, and are not present when (1) fluidbox is closed and (2) fluidbox is fully open.

**Comment by dergraph** [comment] 2015-03-22 16:09
mhm ok so i have images wrap in anchors, link and img src are identical.
once they are visible in the layout there is no additional loading required.
but in the dom i do see the fluidbox-loader …

**Comment by dergraph** [comment] 2015-03-22 20:04
the animation should be in this selector. (currently is not)

.fluidbox-loading .fluidbox-loader::before {
	opacity: 1;
	transition-delay: 0s;

	-webkit-animation: fluidboxLoading 1s infinite;
	animation: fluidboxLoading 1s infinite;
}

**Comment by dergraph** [comment] 2015-03-23 09:32
"animation-fill-mode: forwards"

should be used aswell in that case, I believe.

**Comment by terrymun** [comment] 2015-03-27 20:17
Hey guys,

I apologize for the late reply—real life got a bit too busy lately.

Anyway, I released a pre-release (the oxymorous of that name!) for v1.4.4. I think I might have fixed the zooming transition issue afterall—can't seem to be able to replicate it on my end on Firefox, Safari, and Chrome. If all fails, I suggest using `immediateOpen: true` for all. I am considering to remove this feature if this issue does not get resolved in a reasonable fashion, because it has been causing end users a lot of unnecessary frustration, which I am sorry about.

@dergraph, the animation fill mode has been modified, it should look better now. Thank you!

The latest release: 5c8a0895

**Closed** 2015-06-30 08:31 UTC
Labels: css
